import smtplib
import time
import random
import pandas as pd
from email.message import EmailMessage

# ================= 1. ตั้งค่า Dataset =================
DATASETS_CONFIG = {
    "CEAS_08.csv": {"safe": 2, "phish": 2},
    "spear_phishing_dataset.csv": {"safe": 0, "phish": 0}, # spear phishing 
    "synthetic_emails_poisoned.csv": {"safe": 0, "phish": 0}, # bec (ไม่มี safe)
    "proofpoint_email.csv": {"safe": 0, "phish": 0}, # malware attachment
    "good_emails_all.csv": {"safe": 0, "phish": 0},
    "spam_emails_all.csv": {"safe": 0, "phish": 0}
}

# ================= 2. ฟังก์ชันจัดฟอร์แมตข้อมูล (Normalize) =================
def normalize_dataset(filename, df):
    if filename in ["CEAS_08.csv", "spear_phishing_dataset.csv"]:
        if 'label' in df.columns:
            df['label'] = pd.to_numeric(df['label'], errors='coerce').fillna(0).astype(int)
            
    elif filename == "synthetic_emails_poisoned.csv":
        df['label'] = 1 
        df['sender'] = "ceo.urgent@company.com" 
        
    elif filename == "proofpoint_email.csv":
        if 'phishScore' in df.columns:
            df['label'] = df['phishScore'].apply(lambda x: 1 if pd.notna(x) and float(x) > 80 else 0)
        else:
            df['label'] = 0
        df['body'] = "URGENT ACTION REQUIRED:\n\nPlease review the attached document immediately."

    if filename in ["good_emails_all.csv", "spam_emails_all.csv"]:
        df['sender'] = df['mail'] # ใช้คอลัมน์ mail เป็น sender
        # คอลัมน์ label ในไฟล์นี้เป็นคำว่า "Good" หรือ "Spam" เลยต้องแปลงเป็น 0 กับ 1
        df['label'] = df['label'].apply(lambda x: 1 if str(x).strip().lower() == 'spam' else 0)
        df['subject'] = "System Alert: Server Notification" # สร้างหัวข้อจำลอง
        df['body'] = "This is an automated message generated by the mail server." # สร้างเนื้อหาจำลองเพราะไฟล์ไม่มี Body

    for col in ['sender', 'subject', 'body']:
        if col not in df.columns:
            df[col] = "Unknown"
            
    return df

# ================= 3. ฟังก์ชันโหลดและสุ่มข้อมูล =================
def load_and_sample_emails():
    emails_to_send = []
    print("📂 เริ่มกระบวนการเตรียมข้อมูลจาก Multi-Dataset...")
    
    for filename, config in DATASETS_CONFIG.items():
        num_safe = config.get("safe", 0)
        num_phish = config.get("phish", 0)
        
        if num_safe == 0 and num_phish == 0:
            continue
            
        try:
            print(f"  -> กำลังดึง {filename} (เป้าหมาย: Safe {num_safe}, Phish {num_phish})")
            df = pd.read_csv(filename, on_bad_lines='skip')
            df = normalize_dataset(filename, df)
            
            df_safe = df[df['label'] == 0]
            df_phish = df[df['label'] == 1]
            
            actual_safe = min(num_safe, len(df_safe))
            actual_phish = min(num_phish, len(df_phish))
            
            sampled_safe = df_safe.sample(n=actual_safe) if actual_safe > 0 else pd.DataFrame()
            sampled_phish = df_phish.sample(n=actual_phish) if actual_phish > 0 else pd.DataFrame()
            
            combined_sample = pd.concat([sampled_safe, sampled_phish])
            
            for _, row in combined_sample.iterrows():
                is_phish = (row['label'] == 1)
                sender_email = str(row['sender']) if pd.notna(row['sender']) else "unknown@domain.com"
                
                reply_to_email = "scammer_99@gmail.com" if (is_phish and "company.com" in sender_email) else sender_email

                # 💥 ไฮไลต์: จำลองชื่อไฟล์ไวรัส สำหรับ Proofpoint หรือเมล์ที่มีคำว่า Invoice/Statement 💥
                fake_attachment = None
                subject_text = str(row['subject']).lower() if pd.notna(row['subject']) else ""
                
                if is_phish and (filename == "proofpoint_email.csv" or "statement" in subject_text or "invoice" in subject_text or "wire" in subject_text):
                    # สุ่มนามสกุลไฟล์อันตรายแนบไปให้
                    fake_attachment = random.choice(["invoice_overdue.exe", "compensation_report.zip", "wire_transfer.vbs"])

                emails_to_send.append({
                    "source": filename,
                    "subject": str(row['subject']) if pd.notna(row['subject']) else "No Subject",
                    "sender": sender_email,
                    "reply_to": reply_to_email,
                    "body": str(row['body']) if pd.notna(row['body']) else "",
                    "type": "🔴 PHISHING" if is_phish else "🟢 SAFE",
                    "attachment_name": fake_attachment # เก็บชื่อไฟล์ที่จะแนบ
                })
                
        except Exception as e:
            print(f"     ❌ Error ในไฟล์ {filename}: {e}")

    random.shuffle(emails_to_send)
    return emails_to_send

# ================= 4. ฟังก์ชันยิงเข้า Gateway พร้อมแนบไฟล์ =================
def send_email_to_gateway(email_data):
    msg = EmailMessage()
    msg.set_content(email_data["body"])
    msg['Subject'] = email_data["subject"]
    msg['From'] = email_data["sender"]
    msg['Reply-To'] = email_data["reply_to"]
    msg['To'] = "victim@company.com"

    # 💥 สร้างและแนบไฟล์จำลอง (Fake Payload) เข้าไปในอีเมล 💥
    if email_data["attachment_name"]:
        fake_file_content = b"This is a simulated malware payload for Capstone testing."
        msg.add_attachment(
            fake_file_content, 
            maintype='application', 
            subtype='octet-stream', 
            filename=email_data["attachment_name"]
        )

    try:
        # ยิงเข้าพอร์ต 2525 (พอร์ตจำลอง Gateway ของเรา)
        with smtplib.SMTP('127.0.0.1', 2526) as server:
            server.send_message(msg)
        
        att_alert = f" [📁 แนบไฟล์: {email_data['attachment_name']}]" if email_data["attachment_name"] else ""
        print(f"✅ ส่งสำเร็จ! | {email_data['type']} | {email_data['source']}{att_alert}")
    except Exception as e:
        print(f"❌ ส่งไม่สำเร็จ: {e}")# ================= 3. ฟังก์ชันโหลดและสุ่มข้อมูล =================
def load_and_sample_emails():
    emails_to_send = []
    print("📂 เริ่มกระบวนการเตรียมข้อมูลจาก Multi-Dataset...")
    
    for filename, config in DATASETS_CONFIG.items():
        num_safe = config.get("safe", 0)
        num_phish = config.get("phish", 0)
        
        if num_safe == 0 and num_phish == 0:
            continue
            
        try:
            print(f"  -> กำลังดึง {filename} (เป้าหมาย: Safe {num_safe}, Phish {num_phish})")
            df = pd.read_csv(filename, on_bad_lines='skip')
            df = normalize_dataset(filename, df)
            
            df_safe = df[df['label'] == 0]
            df_phish = df[df['label'] == 1]
            
            actual_safe = min(num_safe, len(df_safe))
            actual_phish = min(num_phish, len(df_phish))
            
            sampled_safe = df_safe.sample(n=actual_safe) if actual_safe > 0 else pd.DataFrame()
            sampled_phish = df_phish.sample(n=actual_phish) if actual_phish > 0 else pd.DataFrame()
            
            combined_sample = pd.concat([sampled_safe, sampled_phish])
            
            for _, row in combined_sample.iterrows():
                is_phish = (row['label'] == 1)
                sender_email = str(row['sender']) if pd.notna(row['sender']) else "unknown@domain.com"
                
                reply_to_email = "scammer_99@gmail.com" if (is_phish and "company.com" in sender_email) else sender_email

                fake_attachment = None
                subject_text = str(row['subject']).lower() if pd.notna(row['subject']) else ""
                
                # 💥 อัปเกรด: ดึงประเภทไฟล์แนบมาจาก Dataset โดยตรง (สำหรับ Spear Phishing) 💥
                if filename == "spear_phishing_dataset.csv" and is_phish:
                    att_type = str(row.get('attachment_type', 'None')).lower()
                    if att_type != 'none' and att_type != 'nan':
                        fake_attachment = f"confidential_document.{att_type}"
                        
                # 💥 กฎเดิมสำหรับไฟล์อื่นๆ 💥
                elif is_phish and (filename == "proofpoint_email.csv" or "statement" in subject_text or "invoice" in subject_text or "wire" in subject_text):
                    fake_attachment = random.choice(["invoice_overdue.exe", "compensation_report.zip", "wire_transfer.vbs"])

                emails_to_send.append({
                    "source": filename,
                    "subject": str(row['subject']) if pd.notna(row['subject']) else "No Subject",
                    "sender": sender_email,
                    "reply_to": reply_to_email,
                    "body": str(row['body']) if pd.notna(row['body']) else "",
                    "type": "🔴 PHISHING" if is_phish else "🟢 SAFE",
                    "attachment_name": fake_attachment
                })
                
        except Exception as e:
            print(f"     ❌ Error ในไฟล์ {filename}: {e}")

    random.shuffle(emails_to_send)
    return emails_to_send

# ================= 4. ฟังก์ชันยิงเข้า Gateway พร้อมแนบไฟล์ =================
def send_email_to_gateway(email_data):
    msg = EmailMessage()
    msg.set_content(email_data["body"])
    msg['Subject'] = email_data["subject"]
    msg['From'] = email_data["sender"]
    msg['Reply-To'] = email_data["reply_to"]
    
    # 💥 อัปเกรด: เปลี่ยนเป้าหมายเป็นบุคคลสำคัญ (High-Value Target) 💥
    # เพื่อให้ Stage 2 ของเราจัดหมวดหมู่เป็น Spear Phishing ได้สำเร็จ
    if "spear" in email_data["source"]:
        msg['To'] = "ceo@company.com" 
    else:
        msg['To'] = "victim@company.com"

    if email_data["attachment_name"]:
        fake_file_content = b"This is a simulated payload for testing."
        msg.add_attachment(
            fake_file_content, 
            maintype='application', 
            subtype='octet-stream', 
            filename=email_data["attachment_name"]
        )

    try:
        with smtplib.SMTP('127.0.0.1', 2526) as server:
            server.send_message(msg)
        
        att_alert = f" [📁 แนบไฟล์: {email_data['attachment_name']}]" if email_data["attachment_name"] else ""
        print(f"✅ ส่งสำเร็จ! | {email_data['type']} | {email_data['source']}{att_alert}")
    except Exception as e:
        print(f"❌ ส่งไม่สำเร็จ: {e}")

# ================= 5. รันระบบ =================
if __name__ == '__main__':
    print("🚀 เริ่มระบบจำลองยิงอีเมล (Aggregated Engine)")
    print("-" * 60)
    
    emails_list = load_and_sample_emails()
    total_emails = len(emails_list)
    
    if total_emails == 0:
        print("❌ ไม่มีอีเมลในคิว ตรวจสอบชื่อไฟล์อีกครั้ง")
        exit()

    for i, email_data in enumerate(emails_list, start=1):
        print(f"\n[{i}/{total_emails}] กำลังยิง...")
        send_email_to_gateway(email_data)
        
        if i < total_emails:
            for sec in range(16, 0, -1):
                print(f" ⏳ รออีก {sec} วินาที...  ", end='\r')
                time.sleep(1)
            print("                       ", end='\r') 
            
    print("\n" + "=" * 60)
    print("ยิง Dataset ทดสอบเสร็จสมบูรณ์!")